package com.dong.foodsect.volleydemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dong.foodsect.volleydemo.RecentSearchBean;
import com.dong.foodsect.volleydemo.CollectBean;

import com.dong.foodsect.volleydemo.RecentSearchBeanDao;
import com.dong.foodsect.volleydemo.CollectBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentSearchBeanDaoConfig;
    private final DaoConfig collectBeanDaoConfig;

    private final RecentSearchBeanDao recentSearchBeanDao;
    private final CollectBeanDao collectBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentSearchBeanDaoConfig = daoConfigMap.get(RecentSearchBeanDao.class).clone();
        recentSearchBeanDaoConfig.initIdentityScope(type);

        collectBeanDaoConfig = daoConfigMap.get(CollectBeanDao.class).clone();
        collectBeanDaoConfig.initIdentityScope(type);

        recentSearchBeanDao = new RecentSearchBeanDao(recentSearchBeanDaoConfig, this);
        collectBeanDao = new CollectBeanDao(collectBeanDaoConfig, this);

        registerDao(RecentSearchBean.class, recentSearchBeanDao);
        registerDao(CollectBean.class, collectBeanDao);
    }
    
    public void clear() {
        recentSearchBeanDaoConfig.clearIdentityScope();
        collectBeanDaoConfig.clearIdentityScope();
    }

    public RecentSearchBeanDao getRecentSearchBeanDao() {
        return recentSearchBeanDao;
    }

    public CollectBeanDao getCollectBeanDao() {
        return collectBeanDao;
    }

}
